platforms:
  Azure:
    sku: Standard_DS2_v2
targets:
  - name: Debian
    platform: Azure
    image: credativ:Debian:9:9.0.201706190

  - name: Ubuntu
    platform: Azure
    image: UbuntuLTS

criteria:
    - module: smoke
