name: LISA/Pytest CI Workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Setup bootstrap Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry for Linux
        if: runner.os == 'Linux'
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Poetry for Windows
        if: runner.os == 'Windows'
        run: |
          (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python
          echo "$env:USERPROFILE\.poetry\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Python dependencies
        run: poetry install

        # TODO: There's a bug in Poetry where `poetry run lisa` tries
        # to call the Bash script it generated instead of `lisa.cmd`,
        # which of course fails on Windows.
      - name: Run self tests
        run: poetry run pytest --verbose --playbook=playbooks/test.yaml --setup-show selftests/

      - name: Run semantic analysis
        run: poetry run pytest --tb=auto --flake8 --mypy -m "flake8 or mypy"
